%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotification_AdminPropertiesAdmin
%% Source: /home/gleber/code/otp/lib/cosNotification/src/CosNotification.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFICATION_ADMINPROPERTIESADMIN_HRL).
-define(COSNOTIFICATION_ADMINPROPERTIESADMIN_HRL, true).




-endif.


