%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyChannelAdmin_SequenceProxyPullConsumer
%% Source: /home/gleber/code/otp/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCHANNELADMIN_SEQUENCEPROXYPULLCONSUMER_HRL).
-define(COSNOTIFYCHANNELADMIN_SEQUENCEPROXYPULLCONSUMER_HRL, true).




-endif.


