%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyChannelAdmin_ProxyPushConsumer
%% Source: /home/gleber/code/otp/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCHANNELADMIN_PROXYPUSHCONSUMER_HRL).
-define(COSNOTIFYCHANNELADMIN_PROXYPUSHCONSUMER_HRL, true).




-endif.


