%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_PullConsumer
%% Source: /home/gleber/code/otp/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_PULLCONSUMER_HRL).
-define(COSNOTIFYCOMM_PULLCONSUMER_HRL, true).




-endif.


