%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosNotifyFilter
%% Source: /home/gleber/code/otp/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSNOTIFYFILTER_HRL).
-define(OE_COSNOTIFYFILTER_HRL, true).




-endif.


