%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosEventComm_CAdmin
%% Source: /home/gleber/code/otp/lib/cosEvent/src/cosEventApp.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTCOMM_CADMIN_HRL).
-define(OE_COSEVENTCOMM_CADMIN_HRL, true).




-endif.


