%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyFilter_InvalidGrammar
%% Source: /home/gleber/code/otp/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyFilter_InvalidGrammar').
-ic_compiled("4_3_5").


-include("CosNotifyFilter.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyFilter/InvalidGrammar:1.0",
                   "InvalidGrammar",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyFilter/InvalidGrammar:1.0".

%% returns name
name() -> "CosNotifyFilter_InvalidGrammar".



