%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyFilter_FilterIDSeq
%% Source: /home/gleber/code/otp/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyFilter_FilterIDSeq').
-ic_compiled("4_3_5").


-include("CosNotifyFilter.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_sequence,tk_long,0}.

%% returns id
id() -> "IDL:omg.org/CosNotifyFilter/FilterIDSeq:1.0".

%% returns name
name() -> "CosNotifyFilter_FilterIDSeq".



