%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosTimerEvent
%% Source: /home/gleber/code/otp/lib/cosTime/src/CosTimerEvent.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSTIMEREVENT_HRL).
-define(OE_COSTIMEREVENT_HRL, true).




-endif.


