%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosPropertyService_FixedProperty
%% Source: /home/gleber/code/otp/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosPropertyService_FixedProperty').
-ic_compiled("4_3_5").


-include("CosPropertyService.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosPropertyService/FixedProperty:1.0",
                   "FixedProperty",[]}.

%% returns id
id() -> "IDL:omg.org/CosPropertyService/FixedProperty:1.0".

%% returns name
name() -> "CosPropertyService_FixedProperty".



