%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_stack
%% Source: /home/gleber/code/otp/lib/orber/examples/Stack/stack.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_STACK_HRL).
-define(OE_STACK_HRL, true).




-endif.


