%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: StackModule_StackFactory
%% Source: /home/gleber/code/otp/lib/orber/examples/Stack/stack.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(STACKMODULE_STACKFACTORY_HRL).
-define(STACKMODULE_STACKFACTORY_HRL, true).




-endif.


