%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: StackModule_EmptyStack
%% Source: /home/gleber/code/otp/lib/orber/examples/Stack/stack.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('StackModule_EmptyStack').
-ic_compiled("4_3_5").


-include("StackModule.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:StackModule/EmptyStack:1.0","EmptyStack",[]}.

%% returns id
id() -> "IDL:StackModule/EmptyStack:1.0".

%% returns name
name() -> "StackModule_EmptyStack".



