%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin_ProxyPullSupplier
%% Source: /home/gleber/code/otp/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_PROXYPULLSUPPLIER_HRL).
-define(COSEVENTCHANNELADMIN_PROXYPULLSUPPLIER_HRL, true).




-endif.


