%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventComm_PushSupplier
%% Source: /home/gleber/code/otp/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCOMM_PUSHSUPPLIER_HRL).
-define(COSEVENTCOMM_PUSHSUPPLIER_HRL, true).




-endif.


