%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosEventChannelAdmin
%% Source: /home/gleber/code/otp/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTCHANNELADMIN_HRL).
-define(OE_COSEVENTCHANNELADMIN_HRL, true).




-endif.


