%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: erlang_binary
%% Source: /home/gleber/code/otp/lib/ic/include/erlang.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module(erlang_binary).
-ic_compiled("4_3_5").


-include("erlang.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_sequence,tk_octet,0}.

%% returns id
id() -> "IDL:erlang/binary:1.0".

%% returns name
name() -> "erlang_binary".



