%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: erlang
%% Source: /home/gleber/code/otp/lib/ic/include/erlang.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(ERLANG_HRL).
-define(ERLANG_HRL, true).


-record(erlang_pid, {node, num, serial, creation}).
-record(erlang_port, {node, id, creation}).
-record(erlang_ref, {node, id, creation}).


-endif.


