%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_OrberIFR
%% Source: /home/gleber/code/otp/lib/orber/src/OrberIFR.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_ORBERIFR_HRL).
-define(OE_ORBERIFR_HRL, true).




-endif.


