%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: m_i
%% Source: /home/gleber/code/otp/lib/ic/examples/pre_post_condition/ex.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(M_I_HRL).
-define(M_I_HRL, true).




-endif.


