%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_ex
%% Source: /home/gleber/code/otp/lib/ic/examples/pre_post_condition/ex.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_EX_HRL).
-define(OE_EX_HRL, true).




-endif.


