%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosEventDomainAdmin
%% Source: /home/gleber/code/otp/lib/cosEventDomain/src/CosEventDomainAdmin.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTDOMAINADMIN_HRL).
-define(OE_COSEVENTDOMAINADMIN_HRL, true).




-endif.


