%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosPropertyService_PropertySetDefFactory
%% Source: /home/gleber/code/otp/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSPROPERTYSERVICE_PROPERTYSETDEFFACTORY_HRL).
-define(COSPROPERTYSERVICE_PROPERTYSETDEFFACTORY_HRL, true).




-endif.


