%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosFileTransfer_FileIterator
%% Source: /home/gleber/code/otp/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSFILETRANSFER_FILEITERATOR_HRL).
-define(COSFILETRANSFER_FILEITERATOR_HRL, true).




-endif.


