%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNaming_NamingContextExt_AlreadyBound
%% Source: /home/gleber/code/otp/lib/orber/COSS/CosNaming/cos_naming_ext.idl
%% IC vsn: 4.3.5
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNaming_NamingContextExt_AlreadyBound').
-ic_compiled("4_3_5").


-include("CosNaming_NamingContextExt.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNaming/NamingContext/AlreadyBound:1.0",
                   "AlreadyBound",[]}.

%% returns id
id() -> "IDL:CosNaming/NamingContextExt/AlreadyBound:1.0".

%% returns name
name() -> "CosNaming_NamingContextExt_AlreadyBound".



