%%% This file was automatically generated by snmpc_mib_to_hrl version 4.25.1
%%% Date: 23-Jul-2014::07:15:59
-ifndef('OTP-TC').
-define('OTP-TC', true).

%% Oids

-define(otpTcModule, [1,3,6,1,4,1,193,19,1,1,2]).


%% Range values


%% Default values

-endif.
